from django.urls import path
from schedule import views

urlpatterns = [
    path('', views.index),
    path('ask_registration', views.ask_registration),
    path('privacy_policy', views.privacy_policy),
    path('register', views.register),
    path('login', views.login),
    path('not_participant', views.not_participant),
    path('select_city', views.select_city),
    path('select_temple', views.select_temple),
    path('select_mass', views.select_mass),
    path('confirm_reservation', views.confirm_reservation),
    path('perform_reservation', views.perform_reservation),
    path('confirmation', views.confirmation),
    path('already_inscribed', views.already_inscribed),
    path('full_mass', views.full_mass),
    path('ask_admin_login', views.ask_admin_login),
    path('admin_login', views.admin_login),
    path('logout', views.logout),
    path('temple', views.temple),
    path('ask_create_mass', views.ask_create_mass),
    path('create_mass', views.create_mass),
    path('mass_history', views.mass_history),
    path('ask_search_participant', views.ask_search_participant),
    path('search_participant', views.search_participant),
    path('consult_mass', views.consult_mass),
    path('consult_participant', views.consult_participant),
    path('modify_participant', views.modify_participant),
    path('ask_delete_participant', views.ask_delete_participant),
    path('delete_participant', views.delete_participant),
    path('ask_confirm_mass', views.ask_confirm_mass),
    path('filter_participants', views.filter_participants),
    path('confirm_mass', views.confirm_mass),
    path('ask_remove_mass', views.ask_remove_mass),
    path('remove_mass', views.remove_mass),
]
